apiVersion: v2
name: runicSystem
version: 1.2.0
description: indexer of glyphs lexicon based
home: https://github.com/kast-spells
sources:
  - https://github.com/kast-spells/kast-system
maintainers:
  - name: namen malkav
    email: namenmalkav@gmail.com
  - name: laaledesiempre
    email: laaledesiempre@disroot.org